pool: 'default'
  # vmImage: windows-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Get-Process | Out-File -FilePath $(Agent.BuildDirectory)\a\Process.txt
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\a'
    publishLocation: 'pipeline'

- download: current
  displayName: Get pipeline artifacts files
  retryCountOnTaskFailure: 3